# AnCasino v2.1
# @author: GrayWolf336 <graywolf336@craftyn.com>
# @license: GPLv3
# @OrginalAuthor: Darazo <darazo.dawning@gmail.com>
# 
# Instructions for this configuration file can be found at the BukkitDev page:
# http://dev.bukkit.org/server-mods/CasinoSlots/
options:
  track-statistics: true
  allow-diagonal-winnings: true
  enable-slot-protection: true
  chat:
    display-plugin-prefix: true
    plugin-prefix: '[Casino]'
    plugin-prefix-color: '&c'
    chat-color: '&a'
types:
  default:
    cost: 100
    create-cost: 1000
    reel:
    - 42,43
    - 41,24
    - 57,15
    - 46,18
    - 103,19
    - 49,4
    - 3,10
    rewards:
      '42':
        message: Winner - 3 iron blocks! $175 awarded.
        money: 175.0
      '41':
        message: Winner - 3 gold blocks! $300 awarded.
        money: 300.0
      '57':
        message: Winner - 3 diamond blocks! $750 awarded.
        money: 750.0
      '46':
        action: kill
        message: Winne-
        money: 0.0
      '103':
        action: give 103 64
        message: Winner - 3 ..melons? Nom.
        money: 0.0
    messages:
      insufficient-funds: You can't afford to use this.
      in-use: This slot machine is already in use.
      no-win: No luck this time.
      start: '[cost] removed from your account. Let''s roll!'
      help:
      - 'Instructions:'
      - Get 3 in a row in order to win. $100 per spin.
      - '3 iron blocks: $175'
      - '3 gold blocks: $300'
      - '3 diamond blocks: $750'
      - '3 melon blocks: stack of melons'
  actionslot:
    cost: 100
    create-cost: 1000
    reel:
    - 46,1
    - 124, 1
    - 90, 1
    - 51, 1
    - 103, 1
    rewards:
      '124':
        action: goblind
        message: Winne- You can't see now!
        money: 0.0
      '46':
        action: kill
        message: Winne-
        money: 0.0
      '90':
        action: drugup
        message: Winne- Kids, drugs are bad!
      '51':
        action: fire
        message: Winne- Fire hurts! Don't mess with hit.
        money: 0.0
      '103':
        action: give 103 64
        message: Winner - 3 ..melons? Nom.
        money: 0.0
    messages:
      insufficient-funds: You can't afford to use this.
      in-use: This slot machine is already in use.
      no-win: No luck this time.
      start: '[cost] removed from your account. Let''s roll!'
      help:
      - 'Instructions:'
      - Get 3 in a row in order to win. $100 per spin.
      - '3 tnt blocks: Death!'
      - '3 on redstone lamps: You go Blind!'
      - '3 melon blocks: stack of melons'
      - '3 portal blocks: Get drugged'
      - '3 fires: Catch on fire'